Repository kalviumcommunity/s64_HarshSingh_CapStone_ReCarNation, pull requests merged in 2025-06, with the labels that each got.

#74 Otp
  backend/config/cookieConfig.js
  backend/config/firebase.js
  backend/features/auth/authMiddleware/combinedAuthMiddleware.js
  backend/features/auth/authMiddleware/firebaseMiddleware.js
  backend/features/auth/authMiddleware/passport.js
  backend/features/auth/verificationController.js
  backend/features/auth/verificationRoutes.js
  backend/model/userModel.js
  frontend/src/components/ErrorBoundary.jsx
  frontend/src/components/navbar.jsx
  frontend/src/context/AuthContext.jsx
  frontend/src/lib/axios.js
  frontend/src/lib/firebase.js
  frontend/src/pages/apiService.js
  frontend/src/pages/auth.jsx
  frontend/src/pages/profilePages/concent.jsx
Labels: Review effort 3/5

#76 bruno api added
  .DS_Store
  backend/API_Testing_Bruno/Products_Model.bru
  backend/API_Testing_Bruno/User_Model.bru
  backend/API_Testing_Bruno/Wishlist_Model.bru
  backend/API_Testing_Bruno/bruno.json
  backend/config/cookieConfig.js
  backend/features/auth/authMiddleware/googleController.js
  frontend/src/pages/home.jsx
Labels: Review effort 2/5

#79 Keeping up to date with origin
  backend/config/cookieConfig.js
Labels: Review effort 2/5, Possible security concern

#80 navbar updated
  frontend/src/components/navbar.jsx
Labels: Review effort 2/5

#86 added raypay payment api as a payment method
  backend/features/payments/paymentController.js
  backend/features/payments/paymentRoutes.js
  backend/model/orderModel.js
  backend/package-lock.json
  backend/package.json
  backend/server.js
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/pages/orders.jsx
  frontend/src/pages/payment.jsx
  frontend/src/utils/razorpay.js
Labels: Possible security concern, Review effort 4/5
